name       : python-typed-ast
version    : 1.1.0
release    : 1
source     :
    - https://github.com/python/typed_ast/archive/1.1.0.tar.gz : 4a1dc8888f032fec709d947b64b8eeca26b5952c6ea5152780a0e02c715e0ed7
license    : Apache-2.0
component  : programming.python
summary    : Modified fork of CPython's ast module that parses `# type:` comments
description: |
    python-typed-ast is a Python 3 package that provides a Python 2.7 and Python 3 parser similar to the standard ast library
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
