name       : python-typed-ast
version    : 1.4.1
release    : 5
source     :
    - https://github.com/python/typed_ast/archive/1.4.1.tar.gz : 498a6cd88f78e4b2058092ff38c9941d61f4eba2c12b371240ba663f063adf7d
homepage   : https://github.com/python/typed_ast
license    : Apache-2.0
component  : programming.python
summary    : Modified fork of CPython's ast module that parses `# type:` comments
description: |
    python-typed-ast is a Python 3 package that provides a Python 2.7 and Python 3 parser similar to the standard ast library
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
