name       : python-typed-ast
version    : 1.4.3
release    : 6
source     :
    - https://github.com/python/typed_ast/archive/refs/tags/1.4.3.tar.gz : c393d5576856f50189e741c38850e529f38aeb77fd7b40d2d9b1f4340e802faa
homepage   : https://github.com/python/typed_ast
license    : Apache-2.0
component  : programming.python
summary    : Modified fork of CPython's ast module that parses `# type:` comments
description: |
    python-typed-ast is a Python 3 package that provides a Python 2.7 and Python 3 parser similar to the standard ast library
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
