name       : python-typed-ast
version    : 1.4.0
release    : 3
source     :
    - https://github.com/python/typed_ast/archive/1.4.0.tar.gz : bd02998404953db788e9d09c1030c4f0eb9d87986b08bd30e9fc00a8e30d6dd8
license    : Apache-2.0
component  : programming.python
summary    : Modified fork of CPython's ast module that parses `# type:` comments
description: |
    python-typed-ast is a Python 3 package that provides a Python 2.7 and Python 3 parser similar to the standard ast library
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
